"""Generate library/CATALOG.md from the indexed game library.

Walks `library/games/sf-<v>/d<D>-mpv<K>-T<T>/g<N>-seed<S>/` directories,
reads each one's `metadata.json`, and emits both a markdown table
(`library/CATALOG.md`) and a machine-readable index
(`library/catalog.json`).

Designed to be safe to re-run any time (idempotent). If a dataset is
mid-generation (no metadata.json yet but chunks exist), it's listed
with status=partial.

Usage:
    python wm_chess/scripts/catalog.py             # default: ./library/
    python wm_chess/scripts/catalog.py --root /path/to/library
"""
from __future__ import annotations

import argparse
import glob
import json
import os
from pathlib import Path


def _human_bytes(n: int) -> str:
    for unit in ("B", "KB", "MB", "GB", "TB"):
        if n < 1024:
            return f"{n:.1f}{unit}"
        n /= 1024
    return f"{n:.1f}PB"


def _dir_size(path: str) -> int:
    total = 0
    for root, _, files in os.walk(path):
        for f in files:
            try:
                total += os.path.getsize(os.path.join(root, f))
            except OSError:
                pass
    return total


def discover_datasets(library_root: str) -> list[dict]:
    """Return a list of dataset entries under library_root/games/.

    Each entry has:
      sf, depth, multipv, T, games, seed, positions, size_bytes,
      status ("complete" | "partial"), path (relative to library_root)
    """
    games_dir = os.path.join(library_root, "games")
    if not os.path.isdir(games_dir):
        return []

    entries: list[dict] = []
    # Glob 4-level deep: sf-<v>/d<D>-mpv<K>-T<T>/g<N>-seed<S>/
    pattern = os.path.join(games_dir, "sf-*", "d*-mpv*-T*", "g*-seed*")
    for leaf in sorted(glob.glob(pattern)):
        if not os.path.isdir(leaf):
            continue
        rel = os.path.relpath(leaf, library_root)
        size = _dir_size(leaf)
        meta_path = os.path.join(leaf, "metadata.json")
        data_path = os.path.join(leaf, "data.npz")
        chunks_dir = os.path.join(leaf, "chunks")
        has_meta = os.path.exists(meta_path)
        has_data = os.path.exists(data_path)
        has_chunks = os.path.isdir(chunks_dir) and bool(os.listdir(chunks_dir))

        # Parse path segments for fallback config (works even if metadata is missing).
        parts = rel.split(os.sep)
        # ['games', 'sf-18', 'd10-mpv8-T1', 'g4000-seed42']
        sf_part = parts[1].removeprefix("sf-") if len(parts) > 1 else "?"
        cfg_part = parts[2] if len(parts) > 2 else ""
        run_part = parts[3] if len(parts) > 3 else ""

        depth = multipv = temperature = n_games = seed = None
        positions = None
        try:
            for tok in cfg_part.split("-"):
                if tok.startswith("d"):
                    depth = int(tok[1:])
                elif tok.startswith("mpv"):
                    multipv = int(tok[3:])
                elif tok.startswith("T"):
                    temperature = float(tok[1:])
            for tok in run_part.split("-"):
                if tok.startswith("g"):
                    n_games = int(tok[1:])
                elif tok.startswith("seed"):
                    seed = int(tok[4:])
        except (ValueError, IndexError):
            pass

        entry: dict = {
            "sf": sf_part,
            "depth": depth,
            "multipv": multipv,
            "T": temperature,
            "games": n_games,
            "seed": seed,
            "positions": positions,
            "size_bytes": size,
            "size_human": _human_bytes(size),
            "status": "complete" if (has_meta and has_data) else
                      ("partial" if has_chunks else "empty"),
            "path": rel,
        }
        if has_meta:
            try:
                with open(meta_path) as f:
                    md = json.load(f)
                entry["positions"] = md.get("n_positions")
                entry["sf_version"] = md.get("sf_version", sf_part)
                entry["wall_seconds"] = md.get("wall_seconds")
                entry["finished_ts"] = md.get("finished_ts")
            except (OSError, json.JSONDecodeError):
                pass
        entries.append(entry)
    return entries


def render_markdown(entries: list[dict]) -> str:
    lines: list[str] = []
    lines.append("# Game library catalog")
    lines.append("")
    lines.append("Auto-generated by `wm_chess/scripts/catalog.py`. **Don't edit by hand** —")
    lines.append("re-run the script after any data-gen change.")
    lines.append("")
    if not entries:
        lines.append("_The library is empty. Run a data-generation job under `library/games/`._")
        lines.append("")
        return "\n".join(lines)

    n_complete = sum(1 for e in entries if e["status"] == "complete")
    n_partial = sum(1 for e in entries if e["status"] == "partial")
    n_empty = sum(1 for e in entries if e["status"] == "empty")
    total_size = sum(e["size_bytes"] for e in entries)
    lines.append(f"**Summary:** {len(entries)} datasets — "
                 f"{n_complete} complete, {n_partial} partial, {n_empty} empty. "
                 f"Total on disk: {_human_bytes(total_size)}.")
    lines.append("")
    lines.append("| status | sf | depth | mpv | T | games | seed | positions | size | path |")
    lines.append("|---|---|---:|---:|---:|---:|---:|---:|---:|---|")
    for e in entries:
        marker = {"complete": "✅", "partial": "⚠️ partial", "empty": "∅"}.get(e["status"], "?")
        pos = f"{e['positions']:,}" if e.get("positions") else "—"
        lines.append(
            f"| {marker} "
            f"| {e['sf']} "
            f"| {e.get('depth', '?')} "
            f"| {e.get('multipv', '?')} "
            f"| {e.get('T', '?')} "
            f"| {e.get('games', '?')} "
            f"| {e.get('seed', '?')} "
            f"| {pos} "
            f"| {e['size_human']} "
            f"| `{e['path']}` |"
        )
    lines.append("")
    lines.append("## Status legend")
    lines.append("")
    lines.append("- ✅ **complete**: `data.npz` + `metadata.json` present, dataset is ready to train against")
    lines.append("- ⚠️ **partial**: chunks exist but `data.npz` not yet assembled — re-run "
                 "the generator with `--finalize-only` to assemble whatever survived, "
                 "or re-run the same args to continue (workers detect existing chunks)")
    lines.append("- ∅ **empty**: directory exists but has no chunks (likely an aborted run)")
    lines.append("")
    return "\n".join(lines)


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--root", default=str(Path(__file__).resolve().parents[2] / "library"),
                   help="library root directory (default: <repo>/library)")
    p.add_argument("--quiet", action="store_true")
    args = p.parse_args()

    entries = discover_datasets(args.root)

    md_path = os.path.join(args.root, "CATALOG.md")
    json_path = os.path.join(args.root, "catalog.json")
    os.makedirs(args.root, exist_ok=True)
    with open(md_path, "w") as f:
        f.write(render_markdown(entries))
    with open(json_path, "w") as f:
        json.dump({"datasets": entries}, f, indent=2)

    if not args.quiet:
        print(f"wrote {md_path}  ({len(entries)} datasets indexed)")
        print(f"wrote {json_path}")


if __name__ == "__main__":
    main()
